In [251]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
#from pandas_profiling import ProfileReport

In [252]:
Order=pd.read_excel("H:\python\Company X - Order Report.xlsx")
#df1=Order.rename(columns={'ExternOrderNo':"Order_ID"})
#df1.to_excel("H:\python\Company X - Order Report.xlsx",index=False)

invoice=pd.read_excel("H:\python\Courier Company - Invoice.xlsx")

#df2=invoice.rename(columns={'Order ID': 'Order_ID'})
#df2.to_excel("H:\python\Courier Company - Invoice.xlsx",index=False)

SKU=pd.read_excel("H:\python\Company X - SKU Master.xlsx")
PIN=pd.read_excel("H:\python\Company X - Pincode Zones.xlsx")
print(Order.columns)
print(invoice.columns)
print(SKU.columns)
print(PIN.columns)

Index(['Order_ID', 'SKU', 'Order Qty'], dtype='object')
Index(['AWB Code', 'Order_ID', 'Charged Weight', 'Warehouse Pincode',
       'Customer Pincode', 'Zone', 'Type of Shipment', 'Billing Amount (Rs.)'],
      dtype='object')
Index(['SKU', 'Weight (g)'], dtype='object')
Index(['Warehouse Pincode', 'Customer Pincode', 'Zone'], dtype='object')

In [253]:
O=pd.merge(Order,invoice,how="right",on="Order_ID")
Ex=pd.merge(O,SKU,how="left",on="SKU")
data=pd.merge(Ex,PIN,how="inner",on="Customer Pincode")
data

,Order_ID,SKU,Order Qty,AWB Code,Charged Weight,Warehouse Pincode_x,Customer Pincode,Zone_x,Type of Shipment,Billing Amount (Rs.),Weight (g),Warehouse Pincode_y,Zone_y
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d
...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b

In [270]:
data.rename(columns={'Charged Weight':'Charged_Weight','Warehouse Pincode_x':'Company_Warehouse_Pincode',
                     'Customer Pincode':'Company_Customer_Pincode','Zone_x':'Company_Zone',
                     'Warehouse Pincode_y':'X_Warehouse_Pincode','Zone_y':'X_Zone','Weight (g)':'Weight_(g)'},inplace=True)
data.rename(columns={'Company_Zone':'Delivery_Zone_Charged_By_Company','X_Zone':'Delivery_Zones_as_per_X'},inplace=True)
data.rename(columns={'Delivery_Zone_Charged_By_Company':'Delivery_Zone_Charged_By_Courier_Company'},inplace=True)
data.rename(columns={'Charged_Weight':'Total_weight_as_per_Courier_Company_(KG)'},inplace=True)
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5

In [271]:
data.columns

Index(['Order_ID', 'SKU', 'Order Qty', 'AWB Code',
       'Total_weight_as_per_Courier_Company_(KG)', 'Company_Warehouse_Pincode',
       'Company_Customer_Pincode', 'Delivery_Zone_Charged_By_Courier_Company',
       'Type of Shipment', 'Billing Amount (Rs.)', 'Weight_(g)',
       'X_Warehouse_Pincode', 'Delivery_Zones_as_per_X',
       'Weight slab charged by Courier Company (KG)'],
      dtype='object')

In [272]:
data['Total_weight_as_per_X(g)']=data['Order Qty']*data['Weight_(g)']
data['Total_weight_as_per_X(Kg)']=data['Total_weight_as_per_X(g)']/1000

In [273]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350

In [274]:
data.columns

Index(['Order_ID', 'SKU', 'Order Qty', 'AWB Code',
       'Total_weight_as_per_Courier_Company_(KG)', 'Company_Warehouse_Pincode',
       'Company_Customer_Pincode', 'Delivery_Zone_Charged_By_Courier_Company',
       'Type of Shipment', 'Billing Amount (Rs.)', 'Weight_(g)',
       'X_Warehouse_Pincode', 'Delivery_Zones_as_per_X',
       'Weight slab charged by Courier Company (KG)',
       'Total_weight_as_per_X(g)', 'Total_weight_as_per_X(Kg)'],
      dtype='object')

In [275]:
Condition1 = [(data['Total_weight_as_per_Courier_Company_(KG)']<=0.500),
             (data['Total_weight_as_per_Courier_Company_(KG)']>0.500)&(data['Total_weight_as_per_Courier_Company_(KG)']<=1),
             (data['Total_weight_as_per_Courier_Company_(KG)']>1)&(data['Total_weight_as_per_Courier_Company_(KG)']<=1.5),
             (data['Total_weight_as_per_Courier_Company_(KG)']>1.5)&(data['Total_weight_as_per_Courier_Company_(KG)']<=2),
             (data['Total_weight_as_per_Courier_Company_(KG)']>2)&(data['Total_weight_as_per_Courier_Company_(KG)']<=2.5),
             (data['Total_weight_as_per_Courier_Company_(KG)']>2.5)&(data['Total_weight_as_per_Courier_Company_(KG)']<=3),
             (data['Total_weight_as_per_Courier_Company_(KG)']>3)&(data['Total_weight_as_per_Courier_Company_(KG)']<=3.5),
             (data['Total_weight_as_per_Courier_Company_(KG)']>3.5)&(data['Total_weight_as_per_Courier_Company_(KG)']<=4)]

In [276]:
value=[0.5,1,1.5,2,2.5,3,3.5,4]

In [277]:
data['Weight_slab_as_per_X_(KG)']=np.select(Condition,value)

In [278]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822,1.0
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480,0.5
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115,0.5
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127,0.5
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127,0.5
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165,0.5
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350,0.5

In [279]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822,1.0
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480,0.5
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115,0.5
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127,0.5
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127,0.5
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165,0.5
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350,0.5

In [280]:
Condition1 = [(data['Total_weight_as_per_Courier_Company_(KG)']<=0.500),
             (data['Total_weight_as_per_Courier_Company_(KG)']>0.500)&(data['Total_weight_as_per_Courier_Company_(KG)']<=1),
             (data['Total_weight_as_per_Courier_Company_(KG)']>1)&(data['Total_weight_as_per_Courier_Company_(KG)']<=1.5),
             (data['Total_weight_as_per_Courier_Company_(KG)']>1.5)&(data['Total_weight_as_per_Courier_Company_(KG)']<=2),
             (data['Total_weight_as_per_Courier_Company_(KG)']>2)&(data['Total_weight_as_per_Courier_Company_(KG)']<=2.5),
             (data['Total_weight_as_per_Courier_Company_(KG)']>2.5)&(data['Total_weight_as_per_Courier_Company_(KG)']<=3),
             (data['Total_weight_as_per_Courier_Company_(KG)']>3)&(data['Total_weight_as_per_Courier_Company_(KG)']<=3.5),
             (data['Total_weight_as_per_Courier_Company_(KG)']>3.5)&(data['Total_weight_as_per_Courier_Company_(KG)']<=4)]

In [281]:
value=[0.5,1,1.5,2,2.5,3,3.5,4]

In [282]:
data['Weight slab charged by Courier Company (KG)']=np.select(Condition1,value)

In [283]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822,1.0
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480,0.5
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115,0.5
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127,0.5
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127,0.5
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165,0.5
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350,0.5

In [284]:
condition2 = [(data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='b')&
              (data['Weight_slab_as_per_X_(KG)']==0.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='b')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='b')&
              (data['Weight_slab_as_per_X_(KG)']==1.5),
              
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='d')&
              (data['Weight_slab_as_per_X_(KG)']==0.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='d')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='d')&
              (data['Weight_slab_as_per_X_(KG)']==1.5),
              
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='e')&
              (data['Weight_slab_as_per_X_(KG)']==0.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='e')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zones_as_per_X']=='e')&
              (data['Weight_slab_as_per_X_(KG)']==1.5),
              
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='b')&
              (data['Weight_slab_as_per_X_(KG)']==0.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='b')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='b')&
              (data['Weight_slab_as_per_X_(KG)']==1.5),
              
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='d')&
              (data['Weight_slab_as_per_X_(KG)']==0.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='d')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='d')&
              (data['Weight_slab_as_per_X_(KG)']==1.5),
             
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='e')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='e')&
              (data['Weight_slab_as_per_X_(KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zones_as_per_X']=='e')&
              (data['Weight_slab_as_per_X_(KG)']==1.5)]

In [285]:
values = [(data['Billing Amount (Rs.)']+33),(data['Billing Amount (Rs.)']+61.3),(data['Billing Amount (Rs.)']+89.6),
          (data['Billing Amount (Rs.)']+45.4),(data['Billing Amount (Rs.)']+90.2),(data['Billing Amount (Rs.)']+135),
          (data['Billing Amount (Rs.)']+56.6),(data['Billing Amount (Rs.)']+112.1),(data['Billing Amount (Rs.)']+167.6),
          (data['Billing Amount (Rs.)']+45.4),(data['Billing Amount (Rs.)']+110.1),(data['Billing Amount (Rs.)']+166.7),
          (data['Billing Amount (Rs.)']+86.7),(data['Billing Amount (Rs.)']+176.3),(data['Billing Amount (Rs.)']+265.9),
          (data['Billing Amount (Rs.)']+107.3),(data['Billing Amount (Rs.)']+218.3),(data['Billing Amount (Rs.)']+329.3)]

In [286]:
data['Weight_slab_as_per_X_(KG)'].value_counts()

0.5    554
1.0     12
1.5      1
Name: Weight_slab_as_per_X_(KG), dtype: int64

In [287]:
data['Type of Shipment'].value_counts()

Forward charges            517
Forward and RTO charges     50
Name: Type of Shipment, dtype: int64

In [288]:
data['Delivery_Zones_as_per_X'].value_counts()

b    397
d    136
e     34
Name: Delivery_Zones_as_per_X, dtype: int64

In [289]:
data['Expected Charge as per X (Rs.)']=np.select(condition2,values)

In [290]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Expected Charge as per X (Rs.)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822,1.0,225.2
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480,0.5,180.4
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115,0.5,135.6
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127,0.5,135.6
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133,0.5,135.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127,0.5,132.1
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5,132.1
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5,132.1
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165,0.5,78.4
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350,0.5,78.4

In [291]:
condition3 = [(data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==0.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==1),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==2),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==2.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==3),
              
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==0.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==2),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==2.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==3),
              
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==0.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==1),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==2),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==2.5),
              (data['Type of Shipment']=='Forward charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==3),
              
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==0.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==2),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==2.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='b')&
              (data['Weight slab charged by Courier Company (KG)']==3),
              
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==0.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==2),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==2.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='d')&
              (data['Weight slab charged by Courier Company (KG)']==3),
             
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==0.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==1),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==1.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==2),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==2.5),
              (data['Type of Shipment']=='Forward and RTO charges')&(data['Delivery_Zone_Charged_By_Courier_Company']=='e')&
              (data['Weight slab charged by Courier Company (KG)']==3)]

In [292]:
values1=[(data['Billing Amount (Rs.)']+33),(data['Billing Amount (Rs.)']+61.3),(data['Billing Amount (Rs.)']+89.6),
         (data['Billing Amount (Rs.)']+117.9),(data['Billing Amount (Rs.)']+146.2),(data['Billing Amount (Rs.)']+174.5),
         
         (data['Billing Amount (Rs.)']+45.4),(data['Billing Amount (Rs.)']+90.2),(data['Billing Amount (Rs.)']+135),
         (data['Billing Amount (Rs.)']+179.8),(data['Billing Amount (Rs.)']+224.6),(data['Billing Amount (Rs.)']+269.4),
        
         (data['Billing Amount (Rs.)']+56.6),(data['Billing Amount (Rs.)']+112.1),(data['Billing Amount (Rs.)']+167.6),
         (data['Billing Amount (Rs.)']+223.1),(data['Billing Amount (Rs.)']+278.6),(data['Billing Amount (Rs.)']+334.1),
         
         (data['Billing Amount (Rs.)']+45.4),(data['Billing Amount (Rs.)']+110.1),(data['Billing Amount (Rs.)']+166.7),
         (data['Billing Amount (Rs.)']+223.3),(data['Billing Amount (Rs.)']+279.9),(data['Billing Amount (Rs.)']+336.5),
        
         (data['Billing Amount (Rs.)']+86.7),(data['Billing Amount (Rs.)']+176.3),(data['Billing Amount (Rs.)']+265.9),
         (data['Billing Amount (Rs.)']+335.5),(data['Billing Amount (Rs.)']+445.1),(data['Billing Amount (Rs.)']+534.7),
        
         (data['Billing Amount (Rs.)']+107.3),(data['Billing Amount (Rs.)']+218.3),(data['Billing Amount (Rs.)']+329.3),
         (data['Billing Amount (Rs.)']+440.3),(data['Billing Amount (Rs.)']+551.3),(data['Billing Amount (Rs.)']+662.3),]

In [293]:
data['Weight slab charged by Courier Company (KG)'].value_counts()

1.0    261
1.5    106
0.5     78
2.0     52
2.5     41
3.0     27
0.0      2
Name: Weight slab charged by Courier Company (KG), dtype: int64

In [294]:
data['Delivery_Zone_Charged_By_Courier_Company'].value_counts()

d    454
b    108
e      5
Name: Delivery_Zone_Charged_By_Courier_Company, dtype: int64

In [295]:
data['Charges Billed by Courier Company (Rs.)']=np.select(condition3,values1)

In [296]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822,1.0,225.2,225.2
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480,0.5,180.4,225.2
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115,0.5,135.6,0.0
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127,0.5,135.6,0.0
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133,0.5,135.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127,0.5,132.1,173.4
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5,132.1,173.4
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5,132.1,173.4
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165,0.5,78.4,90.8
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350,0.5,78.4,90.8

In [297]:
data['Difference Between Expected Charges and Billed Charges (Rs.)']=data['Expected Charge as per X (Rs.)']-data['Charges Billed by Courier Company (Rs.)']

In [298]:
data

,Order_ID,SKU,Order Qty,AWB Code,Total_weight_as_per_Courier_Company_(KG),Company_Warehouse_Pincode,Company_Customer_Pincode,Delivery_Zone_Charged_By_Courier_Company,Type of Shipment,Billing Amount (Rs.),Weight_(g),X_Warehouse_Pincode,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(g),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.)
0,2001806232,8904223818645,6,1091117222124,1.3,121003,507101,d,Forward charges,135.0,137,121003,d,1.5,822,0.822,1.0,225.2,225.2,0.0
1,2001806232,8904223819147,2,1091117222124,1.3,121003,507101,d,Forward charges,135.0,240,121003,d,1.5,480,0.480,0.5,180.4,225.2,-44.8
2,2001806273,8904223819017,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,115,121003,d,1.0,115,0.115,0.5,135.6,0.0,135.6
3,2001806273,8904223818706,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,127,121003,d,1.0,127,0.127,0.5,135.6,0.0,135.6
4,2001806273,8904223818942,1,1091117222194,1.0,121003,486886,d,Forward charges,90.2,133,121003,d,1.0,133,0.133,0.5,135.6,0.0,135.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,127,121003,b,0.5,127,0.127,0.5,132.1,173.4,-41.3
563,2001809383,8904223818850,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5,132.1,173.4,-41.3
564,2001809383,8904223819468,1,1091117614452,0.5,121003,303702,d,Forward and RTO charges,86.7,240,121003,b,0.5,240,0.240,0.5,132.1,173.4,-41.3
565,2001820978,8904223815859,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,165,121003,b,0.5,165,0.165,0.5,78.4,90.8,-12.4
566,2001820978,8904223817501,1,1091120922803,0.5,121003,313301,d,Forward charges,45.4,350,121003,b,0.5,350,0.350,0.5,78.4,90.8,-12.4

In [299]:
Result=data

In [300]:
#delete unwanted columns
delete_columns = ['Order Qty','Company_Warehouse_Pincode','Company_Customer_Pincode','Type of Shipment',
                  'Billing Amount (Rs.)','Weight_(g)','X_Warehouse_Pincode','Total_weight_as_per_X(g)']

In [301]:
for i in delete_columns:
    Result.drop([i],inplace=True,axis=1)

In [302]:
Result

,Order_ID,SKU,AWB Code,Total_weight_as_per_Courier_Company_(KG),Delivery_Zone_Charged_By_Courier_Company,Delivery_Zones_as_per_X,Weight slab charged by Courier Company (KG),Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.)
0,2001806232,8904223818645,1091117222124,1.3,d,d,1.5,0.822,1.0,225.2,225.2,0.0
1,2001806232,8904223819147,1091117222124,1.3,d,d,1.5,0.480,0.5,180.4,225.2,-44.8
2,2001806273,8904223819017,1091117222194,1.0,d,d,1.0,0.115,0.5,135.6,0.0,135.6
3,2001806273,8904223818706,1091117222194,1.0,d,d,1.0,0.127,0.5,135.6,0.0,135.6
4,2001806273,8904223818942,1091117222194,1.0,d,d,1.0,0.133,0.5,135.6,0.0,135.6
...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,8904223818706,1091117614452,0.5,d,b,0.5,0.127,0.5,132.1,173.4,-41.3
563,2001809383,8904223818850,1091117614452,0.5,d,b,0.5,0.240,0.5,132.1,173.4,-41.3
564,2001809383,8904223819468,1091117614452,0.5,d,b,0.5,0.240,0.5,132.1,173.4,-41.3
565,2001820978,8904223815859,1091120922803,0.5,d,b,0.5,0.165,0.5,78.4,90.8,-12.4
566,2001820978,8904223817501,1091120922803,0.5,d,b,0.5,0.350,0.5,78.4,90.8,-12.4

In [303]:
#Arrnage columns in a given order 
Final_Result=Result[["Order_ID","AWB Code","Total_weight_as_per_X(Kg)","Weight_slab_as_per_X_(KG)","Total_weight_as_per_Courier_Company_(KG)",
                     "Weight slab charged by Courier Company (KG)","Delivery_Zones_as_per_X","Delivery_Zone_Charged_By_Courier_Company",
                     "Expected Charge as per X (Rs.)","Charges Billed by Courier Company (Rs.)","Difference Between Expected Charges and Billed Charges (Rs.)"]]

In [304]:
submission_result=Final_Result

In [305]:
submission_result

,Order_ID,AWB Code,Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Total_weight_as_per_Courier_Company_(KG),Weight slab charged by Courier Company (KG),Delivery_Zones_as_per_X,Delivery_Zone_Charged_By_Courier_Company,Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.)
0,2001806232,1091117222124,0.822,1.0,1.3,1.5,d,d,225.2,225.2,0.0
1,2001806232,1091117222124,0.480,0.5,1.3,1.5,d,d,180.4,225.2,-44.8
2,2001806273,1091117222194,0.115,0.5,1.0,1.0,d,d,135.6,0.0,135.6
3,2001806273,1091117222194,0.127,0.5,1.0,1.0,d,d,135.6,0.0,135.6
4,2001806273,1091117222194,0.133,0.5,1.0,1.0,d,d,135.6,0.0,135.6
...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,1091117614452,0.127,0.5,0.5,0.5,b,d,132.1,173.4,-41.3
563,2001809383,1091117614452,0.240,0.5,0.5,0.5,b,d,132.1,173.4,-41.3
564,2001809383,1091117614452,0.240,0.5,0.5,0.5,b,d,132.1,173.4,-41.3
565,2001820978,1091120922803,0.165,0.5,0.5,0.5,b,d,78.4,90.8,-12.4
566,2001820978,1091120922803,0.350,0.5,0.5,0.5,b,d,78.4,90.8,-12.4

In [306]:
# If condition- To find out the "Total orders where X has been correctly charged"
C_count=[(submission_result["Charges Billed by Courier Company (Rs.)"])==(submission_result["Expected Charge as per X (Rs.)"])]
W1_count = [submission_result["Expected Charge as per X (Rs.)"]]
submission_result["Total orders where X has been correctly charged"]=np.select(C_count,W1_count)

# If condition- To find out the "Total Orders where X has been overcharged"
O_count=[(submission_result["Charges Billed by Courier Company (Rs.)"])>(submission_result["Expected Charge as per X (Rs.)"])]
W2_count=[submission_result["Difference Between Expected Charges and Billed Charges (Rs.)"]]
submission_result["Total Orders where X has been overcharged"]=np.select(O_count,W2_count)

# If condition- To find out the Total Orders where X has been undercharged"
U_count=[(submission_result["Charges Billed by Courier Company (Rs.)"])<(submission_result["Expected Charge as per X (Rs.)"])]
W3_count=[submission_result["Difference Between Expected Charges and Billed Charges (Rs.)"]]
submission_result["Total Orders where X has been undercharged"]=np.select(U_count,W3_count)

In [307]:
#Submission of calculations and result
submission_result

,Order_ID,AWB Code,Total_weight_as_per_X(Kg),Weight_slab_as_per_X_(KG),Total_weight_as_per_Courier_Company_(KG),Weight slab charged by Courier Company (KG),Delivery_Zones_as_per_X,Delivery_Zone_Charged_By_Courier_Company,Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.),Total orders where X has been correctly charged,Total Orders where X has been overcharged,Total Orders where X has been undercharged
0,2001806232,1091117222124,0.822,1.0,1.3,1.5,d,d,225.2,225.2,0.0,225.2,0.0,0.0
1,2001806232,1091117222124,0.480,0.5,1.3,1.5,d,d,180.4,225.2,-44.8,0.0,-44.8,0.0
2,2001806273,1091117222194,0.115,0.5,1.0,1.0,d,d,135.6,0.0,135.6,0.0,0.0,135.6
3,2001806273,1091117222194,0.127,0.5,1.0,1.0,d,d,135.6,0.0,135.6,0.0,0.0,135.6
4,2001806273,1091117222194,0.133,0.5,1.0,1.0,d,d,135.6,0.0,135.6,0.0,0.0,135.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2001809383,1091117614452,0.127,0.5,0.5,0.5,b,d,132.1,173.4,-41.3,0.0,-41.3,0.0
563,2001809383,1091117614452,0.240,0.5,0.5,0.5,b,d,132.1,173.4,-41.3,0.0,-41.3,0.0
564,2001809383,1091117614452,0.240,0.5,0.5,0.5,b,d,132.1,173.4,-41.3,0.0,-41.3,0.0
565,2001820978,1091120922803,0.165,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0
566,2001820978,1091120922803,0.350,0.5,0.5,0.5,b,d,78.4,90.8,-12.4,0.0,-12.4,0.0

In [309]:
#Deploy calculations and result in excel file
submission_result.to_excel("H:\python\Final_Result_Report.xlsx")

In [327]:
#Importing and read final result excel file 
df=pd.read_excel("H:\python\Final_Result_Report.xlsx")

In [331]:
#Creating dataframe for summary table
summary=pd.DataFrame(df)

In [333]:
#Select columns for summary results
df1=summary[["Total orders where X has been correctly charged","Total Orders where X has been overcharged",
         "Total Orders where X has been undercharged"]]

In [335]:
#Deploy summary table result in summary table file
df1.to_excel("H:\python\summary_table.xlsx")